### ISSUE TITLE
出错

### ISSUE THREAD

**Issue by xingroam** [fengmoxi/QiyiFLV2MP4#1]
# 影片: 时代先驱
# 时代先驱中除了比尔盖茨那集其他的都会转换错误

正在抽取视音频数据！
True Frame Rate: 25 (25/1)
Average Frame Rate: 4.91321313744328 (79312000/16142593)
封装为MP4中！请耐心等待！
Cannot find file D:\英格瓦?坎普拉德：给地球装上家具的人-国语720P.264
Error importing D:\英格瓦?坎普拉德：给地球装上家具的人-国语720P.264#trackID=1:par=1:1:name=: Requested URL is not valid or cannot be found
FLV文件D:\英格瓦•坎普拉德：给地球装上家具的人-国语720P.FLV已成功重封装为D:\英格瓦•坎普拉德：给地球装上家具的人-国语720P.mp4！

**Comment by fengmoxi** [comment]
把FLV文件名修改成1.FLV试试

**Comment by xingroam** [comment]
你说的对, 应该就是字符的问题, 我把这些视频中"•"这个字符换成空格就成功了.

**Comment by fengmoxi** [comment]
😁好的！我代码上再处理一下
